### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by SharkWipf** [eliphatfs/zerorf#1]
Great work on this, it looks great.
However, it seems you did not include a license, which makes the code default to rather restrictive terms. Per https://choosealicense.com/no-permission/:

> If you find software that doesn’t have a license, that generally means you have no permission from the creators of the software to use, modify, or share the software. Although a code host such as GitHub may allow you to view and fork the code, this does not imply that you are permitted to use, modify, or share the software for any purpose.

It would be great if you could add a license, as it stands, strictly speaking, it's not even legally allowed to test your code.

Generally speaking, a lot of influential whitepaper code is published under the MIT license, which is very open and free, allowing other projects to build upon your code, though other options are viable too. If you don't have a preference, I'd suggest going with MIT.

**Comment by eliphatfs** [comment]
I missed that. Thank you for pointing it out.

**Comment by SharkWipf** [comment]
Much appreciated!
