### ISSUE TITLE
using the 7th image for reconstruction?

### ISSUE THREAD

**Issue by chengqi0514** [eliphatfs/zerorf#10]
Hello, I noticed you used the results of zero123++ for reconstruction. However, only 6 images were used. Would it be possible to use the input image as the 7th image for reconstruction? If it's feasible, what should be the transformer JSON for this image?

**Comment by eliphatfs** [comment]
If you have the elevation and intrinsics of the input image, you can construct the matrices and fill in the entry. You may need to slightly change the load_image code.
