### ISSUE TITLE
Fail to reproduce OpenIllumination experiments

### ISSUE THREAD

**Issue by UranusITS** [eliphatfs/zerorf#11]
Thank you for your great work.

I'm tring your method on OpenIllumination dataset of 4 views but get wierd result.

https://github.com/eliphatfs/zerorf/assets/38391284/b7042ef4-a312-4a29-9e16-02d69642cbc7

I wonder if it's related to the `world_scale` param or something else. Can you provide OpenIllumination configs in detail to help me reproduce the result of your paper?

Thanks.

**Comment by SarahWeiii** [comment]
Hi we upload the config for openillumination and update the README now
