### ISSUE TITLE
OOM error without object mask

### ISSUE THREAD

**Issue by kkennethwu** [eliphatfs/zerorf#12]
Hi, thanks for your great work !
I'm trying training DTU dataset with downsample 4, where I noticed that there is a OOM error without object mask preprocessing. 

In the DTU data loader I comment this part:

<img width="686" alt="image" src="https://github.com/eliphatfs/zerorf/assets/71262989/b202e0bc-103e-4c3b-a46d-f8a2080cd893">

I wonder what is the reason of this problem, because i use RTX4090 with VRAM 24G :(.
Thanks for your answering !

**Comment by eliphatfs** [comment]
1. Why not use the masks?
2. Maybe the background assumptions are different so the volume is getting filled up to fit the background, leading to severe memory consumptions.
3. As a temporary workaround, you can try to decrease the ray batch size.

**Comment by kkennethwu** [comment]
I see. Thank you for the response. I don't use object mask, because there are not object mask in some scene of DTU.
