### ISSUE TITLE
data

### ISSUE THREAD

**Issue by smallcorns** [eliphatfs/zerorf#14]
How to use your own data set?
The script of OpenIllumination data to download the dataset could not be found?

**Comment by eliphatfs** [comment]
You can convert your own data into the standard NeRF-Synthetic format or write your own data loader.
OpenIllumination link is inside the README.

**Comment by eliphatfs** [comment]
The download script is at https://huggingface.co/datasets/OpenIllumination/OpenIllumination/blob/main/open_illumination.py
