### ISSUE TITLE
Output 3D model

### ISSUE THREAD

**Issue by albb20** [eliphatfs/zerorf#15]
Hi, 
thanks for sharing the great work. I did not find an option/line to output a pointcloud or mesh of the reconstructed models. How can I do it? And how would I switch off rendering, in case I dont want it. 
Thanks for your help.

**Comment by albb20** [comment]
I have overlooked the .glb file, which is a 3D scene file.

**Comment by 2019211753** [comment]
Hi, sorry to bother you. Cloud u please help me find where the .glb file is?

**Comment by 2019211753** [comment]
Could u please help me find it out? Thanks! @eliphatfs
