### ISSUE TITLE
Should i run zero123 image before  running general reconstruction?

### ISSUE THREAD

**Issue by 2019211753** [eliphatfs/zerorf#16]
I created my custom dataset based on the NeRF-synthetic dataset, but there is no validation/test dataset included. When I attempt to run the general reconstruction, I encounter an error stating: no such file 'data/nerf_synthetic/chair/transforms_train.json'.

Upon examining lines 65-67 of the code:
```python
work_dir = "results/%s" % args.proj_name
os.makedirs(work_dir, exist_ok=True)
os.chdir(work_dir)
```
I noticed that the current directory is changed to results/test, which doesn't contain any files. Should I place my dataset in this directory?

**Comment by eliphatfs** [comment]
you can use absolute path for data
