### ISSUE TITLE
Question regarding files in repo

### ISSUE THREAD

**Issue by mache102** [eliphatfs/zerorf#2]
Hi, thanks for your excellent work!

I saw that `OrbitCamera` was imported from `lib/core/ssdnerf_gui.py`, but could not find any references for the `SSDNeRFGUI` class.
Likewise, many of the models in `lib/models/architecture` appear unused. 
I was wondering, are they part of the workflow presented in the paper or additional files for other CV tasks? 

Edit: It seems they are files left over from `SSDNeRF`? Correct me if I'm wrong

**Comment by eliphatfs** [comment]
Yes we borrowed this code base, but may not have used everything in it.

**Comment by mache102** [comment]
Got it, thanks!
