### ISSUE TITLE
TypeError: march_rays_train():

### ISSUE THREAD

**Issue by chengqi0514** [eliphatfs/zerorf#3]
│ /data1/user/yanghaibo/eccv24/zerorf/lib/ops/raymarching/raymarching.py:287 in forward            │
│                                                                                                  │
│   284 │   │   # first pass: write rays, get total number of points M to render                   │
│   285 │   │   rays = torch.empty(N, 2, dtype=torch.int32, device=rays_o.device)  # id, offset,   │
│   286 │   │   get_backend().march_rays_train(rays_o, rays_d, density_bitfield, bound, contract   │
│ ❱ 287 │   │   │   │   │   │   │   │   │      nears, fars, None, None, None, rays, step_counter   │
│   288 │   │                                                                                      │
│   289 │   │   # allocate based on M                                                              │
│   290 │   │   M = step_counter.item()                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: march_rays_train(): incompatible function arguments. The following argument types are supported:
    1. (arg0: at::Tensor, arg1: at::Tensor, arg2: at::Tensor, arg3: float, arg4: float, arg5: int, arg6: int, arg7: int, arg8: int, 
arg9: int, arg10: at::Tensor, arg11: at::Tensor, arg12: at::Tensor, arg13: at::Tensor, arg14: at::Tensor, arg15: at::Tensor, arg16: 
at::Tensor, arg17: at::Tensor) -> None

**Comment by eliphatfs** [comment]
Are you using the raymarching library shipped with the repository (or use the docker)? We made changes to the stabledreamfusion raymarching code to support features like occlusion culling.

**Comment by chengqi0514** [comment]
Hi, thank you for your reply. I can already run it correctly. But I noticed that the final mesh generated was a glb file without texture. Is it possible to export a 3D file with texture?

**Comment by eliphatfs** [comment]
It is not impossible, but difficult to get a 'lossless' result. We do not focus on fine mesh reconstruction and the algorithms exist just to check the geometry for debugging purposes.

**Comment by eliphatfs** [comment]
Please open a new issue if you have further questions; the topic is going beyond the title of this issue.
