### ISSUE TITLE
Question regarding the transform matrix

### ISSUE THREAD

**Issue by aplatyps** [eliphatfs/zerorf#4]
Hi, may I know what is the camera coordinate system used and how is the `meta.json` generated from rendered image dataset? How do we obtain the transform matrix when rendering a custom dataset? Thanks.

**Comment by eliphatfs** [comment]
The camera coordinate system during our ray marching rendering is in OpenCV convention; the meta.json and NeRF-synthetic data is in Blender convention. By the way, I kindly refer you to my library [calibur](https://github.com/eliphatfs/calibur) as a tool to handle the conventions.
The transform matrix is the camera pose (or c2w) matrix.
