### ISSUE TITLE
code and preprocessor of decoder

### ISSUE THREAD

**Issue by ssh0731** [eliphatfs/zerorf#5]
When choose _TensorialGenerator_ as the _self.preprocessor_ in _decoder_, in func _preproc_ of decoder, u take _code_ as the input of _self.preprocessor()_, but the actual input of the preprocessor is the inside fixed _noise_ instead of the passed-in _code_. I'm confused about this.
Besides, the shape of the inside noise is (1, noise_ch, *noise_res), with batch_size=1, so as the output of the preprocessor, doesn't match the required size (num_scenes, *code_size)

**Comment by eliphatfs** [comment]
This is actually an engineering artifact of using the SSDNeRF codebase.
In our implementation, as ZeroRF is per-scene optimization, num_scenes is 1 and code_size is set to the same as the noise shape, so the shapes do not match symbolically but match in value.
And yes the code is unused.

**Comment by ssh0731** [comment]
Thanks!!! I get it now.
