### ISSUE TITLE
march_rays_train ERROR

### ISSUE THREAD

**Issue by xiyufeng2** [eliphatfs/zerorf#7]
When I run the demo: 'python zerorf.py --rep=tensorf --data-dir=path/to/nerf_synthetic --obj=hotdog --n-views=6'

the code went wrong:
get_backend().march_rays_train(rays_o, rays_d, density_bitfield, bound, contract, dt_gamma, max_steps, N, C, H, nears, fars, None, None, None, rays, step_counter, noises)

TypeError: march_rays_train(): incompatible function arguments. The following argument types are supported: 1. (arg0: at::Tensor, arg1: at::Tensor, arg2: at::Tensor, arg3: float, arg4: float, arg5: int, arg6: int, arg7: int, arg8: int, arg9: int, arg10: at::Tensor, arg11: at::Tensor, arg12: at::Tensor, arg13: at::Tensor, arg14: at::Tensor, arg15: at::Tensor, arg16: at::Tensor, arg17: at::Tensor) -> None Invoked with: tensor([[ 1.6088, -1.1919, 1.1559], [-0.2472, -2.1584, -0.7907]...

so, which parameter goes wrong?

**Comment by eliphatfs** [comment]
https://github.com/eliphatfs/zerorf/issues/3#issuecomment-1858901747
